name: Deploy Vite site to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      
      # Instala as dependências com base no package-lock.json
      - run: npm ci
      
      # Gera a pasta dist (build do Vite)
      - run: npm run build
      
      # Copia o arquivo CNAME para a pasta dist
      - run: |
          if [ -f CNAME ]; then
            cp CNAME dist/
            echo "CNAME copiado para dist/"
          else
            echo "Arquivo CNAME não encontrado na raiz"
          fi
      
      # Entrega a pasta dist para o GitHub Pages com configurações completas
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
          name: github-pages
          retention-days: 30

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
